# Generated by Django 5.1 on 2024-11-05 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_is_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='attachments',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_sent',
        ),
        migrations.AlterField(
            model_name='mail',
            name='cc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mail',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddField(
            model_name='mail',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
